import { APIChannel, APIEmoji, APIGuildScheduledEvent, APIGuildWelcomeScreen, APIStageInstance, APISticker, GatewayGuildCreateDispatchData, GatewayPresenceUpdate, GatewayVoiceState, GuildDefaultMessageNotifications, GuildExplicitContentFilter, GuildFeature, GuildHubType, GuildMFALevel, GuildNSFWLevel, GuildPremiumTier, GuildSystemChannelFlags, GuildVerificationLevel } from "discord-api-types/v10";
import { Members } from "./Members";
import { Role } from "./Role";

export class Guild implements GatewayGuildCreateDispatchData {
    joined_at: string;
    large: boolean;
    member_count: number;
    voice_states: Omit<GatewayVoiceState, "guild_id">[];
    afk_channel_id: string;
    afk_timeout: 1800 | 3600 | 60 | 300 | 900;
    application_id: string;
    approximate_member_count?: number;
    approximate_presence_count?: number;
    banner: string;
    channels: APIChannel[];
    default_message_notifications: GuildDefaultMessageNotifications;
    description: string;
    discovery_splash: string;
    emojis: APIEmoji[];
    explicit_content_filter: GuildExplicitContentFilter;
    guild_scheduled_events: APIGuildScheduledEvent[];
    hub_type: GuildHubType;
    icon_hash?: string;
    max_members?: number;
    max_presences?: number;
    id: string;
    name: string;
    icon: string;
    owner: boolean;
    permissions: string;
    features: GuildFeature[];
    permissions_new: string;
    max_stage_video_channel_users?: number;
    system_channel_flags: GuildSystemChannelFlags;
    rules_channel_id: string;
    max_video_channel_users?: number;
    mfa_level: GuildMFALevel;
    nsfw_level: GuildNSFWLevel;
    owner_id: string;
    preferred_locale: string;
    public_updates_channel_id: string;
    premium_progress_bar_enabled: boolean;
    premium_subscription_count?: number;
    premium_tier: GuildPremiumTier;
    presences: GatewayPresenceUpdate[];
    region: string;
    safety_alerts_channel_id: string;
    splash: string;
    stage_instances: APIStageInstance[];
    stickers: APISticker[];
    system_channel_id: string;
    threads: APIChannel[];
    unavailable?: boolean;
    vanity_url_code: string;
    verification_level: GuildVerificationLevel;
    welcome_screen?: APIGuildWelcomeScreen;
    widget_channel_id?: string;
    widget_enabled?: boolean;
    roles: Role[];
    members: Members[];
    public cache: Map<string, this> = new Map();
    constructor() {
        this.joined_at = "";
        this.large = false;
        this.member_count = 0;
        this.voice_states = [];
        this.afk_channel_id = "";
        this.afk_timeout = 300; // Default to 5 minutes
        this.application_id = "";
        this.approximate_member_count = 0;
        this.approximate_presence_count = 0;
        this.banner = "";
        this.channels = [];
        this.default_message_notifications = GuildDefaultMessageNotifications.AllMessages;
        this.description = "";
        this.discovery_splash = "";
        this.emojis = [];
        this.explicit_content_filter = GuildExplicitContentFilter.Disabled;
        this.guild_scheduled_events = [];
        this.hub_type = GuildHubType.Default;
        this.icon_hash = "";
        this.max_members = 0;
        this.max_presences = 0;
        this.id = "";
        this.name = "";
        this.icon = "";
        this.owner = false;
        this.permissions = "";
        this.features = [];
        this.permissions_new = "";
        this.max_stage_video_channel_users = 0;
        this.system_channel_flags = GuildSystemChannelFlags.SuppressJoinNotifications;
        this.rules_channel_id = "";
        this.max_video_channel_users = 0;
        this.mfa_level = GuildMFALevel.None;
        this.nsfw_level = GuildNSFWLevel.Default;
        this.owner_id = "";
        this.preferred_locale = "";
        this.public_updates_channel_id = "";
        this.premium_progress_bar_enabled = false;
        this.premium_subscription_count = 0;
        this.premium_tier = GuildPremiumTier.None;
        this.presences = [];
        this.region = "";
        this.safety_alerts_channel_id = "";
        this.splash = "";
        this.stage_instances = [];
        this.stickers = [];
        this.system_channel_id = "";
        this.threads = [];
        this.unavailable = false;
        this.vanity_url_code = "";
        this.verification_level = GuildVerificationLevel.None;
        this.welcome_screen = undefined;
        this.widget_channel_id = "";
        this.widget_enabled = false;
        this.roles = [];
        this.members = [];
        this.cache = new Map();
    }
    async fetch(id: string): Promise<Guild> {
        // Fetch guild data
        return this.cache.get(id);
    }
}